# Generated by Django 4.0 on 2022-01-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0009_auto_20211207_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedata',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='fname',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='lname',
            field=models.CharField(default='lname', max_length=100),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='resources/pdf_files'),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='phone',
            field=models.CharField(default='123456789', max_length=100),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/resources/profileimages'),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='word_files',
            field=models.FileField(blank=True, null=True, upload_to='resources/word_files'),
        ),
    ]
